core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('a/', include('src.portals.admins.urls', namespace='admins')),
    path('c/', include('src.portals.customer.urls', namespace='customer-portal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portals/admins/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from .views import *

app_name = "admins"
urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('ngo/<int:pk>/change/', NGOUpdateView.as_view(), name='ngo-update'),

    path('projecttype/', ProjectTypeListView.as_view(), name='projecttype-list'),
    path('projecttype/add/', ProjectTypeCreateView.as_view(), name='projecttype-create'),
    path('projecttype/<int:pk>/change/', ProjectTypeUpdateView.as_view(), name='projecttype-update'),
    path('projecttype/<int:pk>/delete/', ProjectTypeDeleteView.as_view(), name='projecttype-delete'),

    path('project/', ProjectListView.as_view(), name='project-list'),
    path('project/add/', ProjectCreateView.as_view(), name='project-create'),
    path('project/<int:pk>/change/', ProjectUpdateView.as_view(), name='project-update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),

    path('donation/', DonationListView.as_view(), name='donation-list'),
    path('donation/<int:pk>/change/', DonationUpdateView.as_view(), name='donation-update'),
    path('donation/<int:pk>/delete/', DonationDeleteView.as_view(), name='donation-delete'),

    path('payment/verification/easypaisa/', PaymentVerificationEasyPaisa.as_view(), name='payment-verification-easypaisa')

]

templates/core/include/admin_header.html
{% load static %}


{#DASHBOARD#}
<li class="nav-item">
    <a class="nav-link dropdown-toggle arrow-none" href="{% url 'admins:dashboard' %}">
        <i class="bx bx-home-circle mr-2"></i>Admin Dashboard
    </a>
</li>


{# FEATURES #}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-components" role="button"
       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="bx bx-collection mr-2"></i>Features
        <div class="arrow-down"></div>
    </a>
    <div class="dropdown-menu" aria-labelledby="topnav-components">
        <a href="{% url 'admins:projecttype-list' %}" class="dropdown-item">Project Types</a>
        <a href="{% url 'admins:project-list' %}" class="dropdown-item">Projects</a>
        <a href="{% url 'admins:donation-list' %}" class="dropdown-item">Donations</a>
    </div>
</li>

{# ROOT ADMIN #}
{% if request.user.is_superuser %}
    <li class="nav-item">
        <a class="nav-link" href="/admin/">
            <i class="bx bx-sitemap mr-2"></i>Root Access
        </a>
    </li>
{% endif %}

{# ROOT ADMIN #}
{% if request.user.is_superuser %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'admins:ngo-update' 1 %}">
            <i class="bx bx-sitemap mr-2"></i>NGO Profile
        </a>
    </li>
{% endif %}

{# ROOT ADMIN #}
{% if request.user.is_superuser %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'admins:payment-verification-easypaisa' %}">
            <i class="bx bx-analyse mr-2"></i>Transaction Verification
        </a>
    </li>
{% endif %}


<li class="nav-item">
    <a class="nav-link" href="/">
        <i class="bx bx-globe mr-2"></i>Website
    </a>
</li>


{# ------------------------------------------------------------------------------------------------------------------ #}

templates/core/include/anonymous_top_nav.html
{% load static %}

{% load static %}

<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="{% url 'home' %}" class="logo logo-dark text-dark">
                                <span class="logo-sm">
                                    <b>COCOGNITO</b>
{#                                    <img src="{% static 'application/images/logo_100.png' %}" alt="" height="21">#}
                                </span>
                    <span class="logo-lg">
                                    <b>COCOGNITO</b>
{#                        <img src="{% static 'application/images/logo_100.png' %}" alt="" height="21">#}
                                </span>
                </a>

                <a href="{% url 'home' %}" class="logo logo-light text-light">
                                <span class="logo-sm">
                                    <b class="lead">COCOGNITO</b>
{#                                    <img src="{% static 'application/images/logo_100.png' %}" alt="" height="21">#}
                                </span>
                    <span class="logo-lg">
                                    <b class="lead">COCOGNITO</b>
{#                        <img src="{% static 'application/images/logo_100.png' %}" alt="" height="21">#}
                                </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 d-lg-none header-item waves-effect waves-light"
                    data-toggle="collapse" data-target="#topnav-menu-content">
                <i class="fa fa-fw fa-bars"></i>
            </button>

        </div>

        <div class="d-flex">


            {# FLAGS #}
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="" src="{% static 'application/images/flags/us.jpg' %}" alt="Header Language"
                         height="16">
                </button>
                <div class="dropdown-menu dropdown-menu-right">

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="{% static 'application/images/flags/spain.jpg' %}" alt="user-image" class="mr-1"
                             height="12"> <span class="align-middle">Spanish</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="{% static 'application/images/flags/germany.jpg' %}" alt="user-image" class="mr-1"
                             height="12"> <span class="align-middle">German</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="{% static 'application/images/flags/italy.jpg' %}" alt="user-image" class="mr-1"
                             height="12"> <span class="align-middle">Italian</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="{% static 'application/images/flags/russia.jpg' %}" alt="user-image" class="mr-1"
                             height="12"> <span class="align-middle">Russian</span>
                    </a>
                </div>


            </div>

            {# FLAGS #}
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa bx bx-power-off"></i> Login</button>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{% url 'account_login' %}">
                        <i class="bx bx-user font-size-16 align-middle mr-1"></i> Student
                    </a>

                    <a class="dropdown-item" href="{% url 'account_login' %}">
                        <i class="bx bx-pencil font-size-16 align-middle mr-1"></i> Parent
                    </a>

                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-primary" href="{% url 'account_login' %}">
                        <i class="bx bxs-check-shield font-size-16 align-middle mr-1"></i> <b>Admin</b>
                    </a>

                </div>
            </div>


        </div>
    </div>
</header>

templates/core/include/customer_header.html
{% load static %}


<li class="nav-item">
    <a class="nav-link" href="{% url 'customer-portal:dashboard' %}">
        <i class="bx bxs-dashboard mr-2"></i>Dashboard
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="{% url 'customer-portal:donation-list' %}">
        <i class="bx bx-clipboard mr-2"></i>Donations
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="/">
        <i class="bx bx-help-circle mr-2"></i>News Feed
    </a>
</li>


templates/core/include/message.html
<div>
    {% if messages %}
    <div class="container">
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-info alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% elif message.tags == 'debug' %}
                <div class="alert alert-dark alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% elif message.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% else %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ message.tags }}! </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}
</div>


templates/core/include/organizer_header.html
{% load static %}


{#DASHBOARD#}
<li class="nav-item">
    <a class="nav-link dropdown-toggle arrow-none" href="{% url 'admins:dashboard' %}">
        <i class="bx bx-home-circle mr-2"></i>Admin Dashboard
    </a>
</li>

{# ROOT ADMIN #}
{% if request.user.is_superuser %}
    <li class="nav-item">
        <a class="nav-link" href="/admin/">
            <i class="bx bx-sitemap mr-2"></i>Root Access
        </a>
    </li>
{% endif %}

{# ROOT ADMIN #}
{% if request.user.is_superuser %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'admins:ngo-update' 1 %}">
            <i class="bx bx-sitemap mr-2"></i>NGO Profile
        </a>
    </li>
{% endif %}


{# FEATURES #}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-components" role="button"
       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="bx bx-collection mr-2"></i>Features
        <div class="arrow-down"></div>
    </a>
    <div class="dropdown-menu" aria-labelledby="topnav-components">
        <a href="{% url 'admins:projecttype-list' %}" class="dropdown-item">Project Types</a>
        <a href="#" class="dropdown-item">Projects</a>
        <a href="#" class="dropdown-item">Donations</a>
    </div>
</li>


{# ------------------------------------------------------------------------------------------------------------------ #}