core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('a/', include('src.portals.admins.urls', namespace='admins')),
    path('c/', include('src.portals.customer.urls', namespace='customer-portal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portals/customer/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import DonationCreateView, DonationListView, DashboardView, SuccessPayment, CancelPayment

app_name = "customer-portal"
urlpatterns = [

    path(
        'dashboard', DashboardView.as_view(), name='dashboard'
    ),
    path('donation/', DonationListView.as_view(), name='donation-list'),
    path('project/<int:pk>/donate/', DonationCreateView.as_view(), name='donate'),
    path('payment-success/',SuccessPayment.as_view(), name="success"),
    path('payment-cancelled/',CancelPayment.as_view(), name="cancel"),

]

src/website/urls.py
from django.urls import path
from .views import HomeView, ProjectView


app_name = 'website'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project-detail'),
]

src/portals/customer/views.py
import stripe
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.forms import ModelForm
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, CreateView, TemplateView
from src.accounts.decorators import customer_required
from src.portals.admins.models import Donation, Project


@method_decorator(customer_required, name='dispatch')
class DashboardView(TemplateView):
    template_name = 'customer/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['donations_count'] = Donation.objects.filter(user=self.request.user).count()
        context['donations_amount_count'] = Donation.objects.filter(user=self.request.user,
                                                                    is_completed=True).aggregate(Sum('amount'))
        context['donations_projects'] = Donation.objects.filter(user=self.request.user, is_completed=True).count()
        context['donations_pending'] = Donation.objects.filter(user=self.request.user, is_completed=False).count()
        return context


@method_decorator(customer_required, name='dispatch')
class NewsFeedView(TemplateView):
    template_name = 'customer/news-feed.html'

    def get_context_data(self, **kwargs):
        context = super(NewsFeedView, self).get_context_data(**kwargs)
        context['projects'] = Project.objects.filter(is_completed=False)
        return context


@method_decorator(customer_required, name='dispatch')
class DonationListView(ListView):
    queryset = Donation.objects.all()
    template_name = 'customer/donation_list.html'

    def get_queryset(self):
        return Donation.objects.filter(user=self.request.user)


class DonateForm(ModelForm):
    class Meta:
        model = Donation
        fields = ['payment_method', 'amount']


stripe.api_key = 'sk_test_51LC794Js59MkLRK8jKm97MecFP4dwcOrxfetIXefvByCaodNGQ1qNdKqaxVBZGD1aW9VTBh69W73T1Ox7LtByRpy00nRXonBff '


@method_decorator(login_required, name='dispatch')
class DonationCreateView(View):

    def get(self, request, pk):
        if request.user.is_superuser or request.user.is_staff:
            messages.warning(request, "Admins are not allowed to donate.")
            return redirect('admins:dashboard')

        project = get_object_or_404(Project.objects.all(), pk=self.kwargs['pk'])
        return render(request, 'customer/donation_form.html', context={'form': DonateForm()})

    def post(self, request, pk):
        form = DonateForm(request.POST)
        project = get_object_or_404(Project.objects.all(), pk=self.kwargs['pk'])

        amount = self.request.POST.get('amount')
        payment_method = self.request.POST.get('payment_method')
        amount_calculation = int(project.donation_amount)+int(amount)
        if amount_calculation <= int(project.required_amount):
            total_amount = int(amount) * 100
            host = self.request.get_host()
            customer = stripe.Customer.create(
                name=self.request.user.username,
                email=self.request.user.email
            )
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                customer=customer,
                submit_type='pay',
                line_items=[
                    {
                        'price_data': {
                            'currency': 'usd',
                            'unit_amount': total_amount,
                            'product_data': {
                                'name': project.name,
                            },
                        },
                        'quantity': 1,
                    },
                ],

                mode='payment',
                success_url='http://' + host + reverse('customer-portal:success') \
                            + '?session_id={CHECKOUT_SESSION_ID}',
                cancel_url='http://{}{}'.format(host, reverse(
                    'customer-portal:cancel')),
            )
            print(checkout_session['payment_intent'])
            donate = Donation(
                user=self.request.user,
                project=project,
                amount=amount,
                payment_method=payment_method,
                transaction_id=checkout_session['payment_intent'],
                stripe_id=checkout_session['id'],
            )

            donate.save()
            return redirect(checkout_session.url, code=303)
        else:
            max_amount = int(project.required_amount) - int(project.donation_amount)
            messages.error(request, f"Your Maximum Donation Limit is {max_amount}$")
            return redirect('customer-portal:donate',pk)

class SuccessPayment(View):
    def get(self, request, *args, **kwargs):
        stripe_id = self.request.GET.get('session_id')

        donation = Donation.objects.get(user=self.request.user, stripe_id=stripe_id)
        donation.is_paid = True
        donation.save()
        context = {
            'invoice': donation
        }
        return render(self.request, 'customer/success.html', context)


class CancelPayment(TemplateView):
    template_name = 'customer/cancel.html'

src/portals/customer/templates/customer/cancel.html
payment cancel

src/portals/customer/templates/customer/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} {{ request.user }} {% endblock %}

{% block base_links %}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="media">
                                <div class="mr-3">
                                    {% if request.user.profile_image %}
                                        <img src="{{ request.user.profile_image.url }}" alt=""
                                             class="avatar-md rounded-circle img-thumbnail">
                                    {% else %}
                                        <img src="{% static 'images/user.png ' %}" alt=""
                                             class="avatar-md rounded-circle img-thumbnail">
                                    {% endif %}
                                </div>
                                <div class="media-body align-self-center">
                                    <div class="text-muted">
                                        <p class="mb-2">Welcome to Charity system</p>
                                        <h5 class="mb-1">
                                            {% if request.user.first_name and request.user.last_name %}
                                                {{ request.user.first_name }} {{ request.user_last_name }}
                                            {% else %}
                                                {{ request.user.username }}
                                            {% endif %}
                                        </h5>
                                        <p class="mb-0 text-danger">
                                            Customer Account
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-8 align-self-center">
                            <div class="text-lg-center mt-4 mt-lg-0">
                                <div class="row text-center">
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-clipboard-list"></i>
                                            </h2>
                                            <small>Total Donations</small>
                                            <h5 class="">{{ donations_count }}</h5>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-clipboard"></i>
                                            </h2>
                                            <small>Approved</small>
                                            <h5 class="mb-0">{{ donations_projects }}</h5>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-exclamation-triangle"></i>
                                            </h2>
                                            <small>Pending</small>
                                            <h5 class="mb-0">{{ donations_pending }}</h5>
                                        </div>
                                    </div>
                                    <div class="col text-success border-left">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-hands-helping text-success"></i>
                                            </h2>
                                            <small>Amount</small>
                                            <h5 class="text-success">$ {{ donations_amount_count.amount__sum }}</h5>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}




src/portals/customer/templates/customer/donation_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} Donation {% endblock %}

{% block page_heading %}
    Donation
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="col-8">

            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.media }}
                        {{ form| crispy }}
                        <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                    </form>
                    <div class="mt-3">
                        <a href="{% url 'admins:donation-list' %}"><i class="fa fa-arrow-left"></i> Back to List</a>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <p class="card-title">
                        <i class="fa fa-exclamation-circle"></i> Steps To Donate.
                    </p>
                    <p class="card-text">
                    <ol>
                        <li>Pay with Stripe
                        </li>
                        <li>Enter amount you want to donate </li>
                        <li>Select project of your choice</li>
                        <li>Select <b>Stripe</b> as your payment method</li>
                        <li>Wait for 24 hours then check the status</li>
                    </ol>
                    </p>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

src/portals/customer/templates/customer/donation_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Donations {% endblock %}
{% block page_heading %}
    Donations
{% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="card">
        <div class="card-body">
            {% if donation_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Project</th>
                            <th>Amount</th>
                            <th>TX ID</th>
                            <th>Created On</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for row in donation_list %}
                            <tr>
                                <td>{{ row.pk }}</td>
                                <td>{{ row.project }}</td>
                                <td>{{ row.amount }}</td>
                                <td>{{ row.transaction_id }}</td>
                                <td>{{ row.created_on }}</td>
                                <td>
                                    {% if row.is_completed %}
                                        <b class="text-success"><i class="fa fa-check-circle"></i> Verified</b>
                                    {% else %}
                                        <b class="text-danger"><i class="fa fa-times-circle"></i> Un-Verified</b>
                                    {% endif %}
                                </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>
                <h5 class="card-title text-danger">No Transactions placed yet.</h5>
                </p>

            {% endif %}
        </div>
    </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}

src/portals/customer/templates/customer/news-feed.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} News Feed {% endblock %}

{% block base_links %}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                </div>
            </div>
        </div>
    </div>


{% endblock %}




src/portals/customer/templates/customer/success.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
    body {
    background: dark;
    margin-top: 120px;
    margin-bottom: 120px;
}


</style>
<div class="row justify-content-center">

    <div class="col-8">
        <div class="text-center">
            <h4>Your Donation is Successfully Transferred</h4>

        </div>




                <div class="row m-5 justify-content-center">
<!--                    <div class="col-md-6 text-center">-->
<!--                        <p class="font-weight-bold mb-4">Client Information</p>-->
<!--                        <p class="mb-1">Email Address : {{invoice.user.email}}</p>-->
<!--                        <p class="mb-1">Username : {{invoice.user.username}}</p>-->
<!--                        <p class="mb-1">Address :{{invoice.user.address}}</p>-->
<!--                        <p class="mb-1">Phone No :{{invoice.user.phone_number}}</p>-->
<!--                    </div>-->

                    <div class="col-md-7 text-center shadow p-5">
                        <p class="font-weight-bold mb-4">Payment Details</p>
                        <p class="mb-1"><span class="text-muted">Transaction Id : </span> {{invoice.transaction_id}}</p>
                        <p class="mb-1"><span class="text-muted">Payment Type: </span> {{invoice.payment_method}}</p>
                        <p class="mb-1"><span class="text-muted">project : </span> {{invoice.project}}</p>
                        <p class="mb-1"><span class="text-muted">Donated Amount: </span> {{invoice.amount}}</p>
                        <p class="mb-1"><span class="text-muted">Is paid : </span> {{invoice.is_paid}}</p>
                        <p class="mb-1 mt-2"><span class="text-muted"><a href="{% url 'website:home' %}">Go Back to Home</a></p>
                    </div>
                </div>



            </div>
        </div>

