core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('a/', include('src.portals.admins.urls', namespace='admins')),
    path('c/', include('src.portals.customer.urls', namespace='customer-portal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portals/customer/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import DonationCreateView, DonationListView, DashboardView, SuccessPayment, CancelPayment

app_name = "customer-portal"
urlpatterns = [

    path(
        'dashboard', DashboardView.as_view(), name='dashboard'
    ),
    path('donation/', DonationListView.as_view(), name='donation-list'),
    path('project/<int:pk>/donate/', DonationCreateView.as_view(), name='donate'),
    path('payment-success/',SuccessPayment.as_view(), name="success"),
    path('payment-cancelled/',CancelPayment.as_view(), name="cancel"),

]

src/website/urls.py
from django.urls import path
from .views import HomeView, ProjectView


app_name = 'website'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project-detail'),
]

src/website/views.py
from django.db.models import Sum
from django.views.generic import TemplateView, DetailView

from src.accounts.models import User
from src.portals.admins.models import Project


class HomeView(TemplateView):
    template_name = 'website/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['users'] = User.objects.all().count()
        context['projects_count'] = Project.objects.all().count()
        context['funds'] = Project.objects.all().aggregate(Sum('donation_amount'))
        context['projects'] = Project.objects.filter(is_completed=False)[:6]
        context['projects_all'] = Project.objects.filter(is_completed=False)
        return context


class ProjectView(DetailView):
    template_name = 'website/project_detail.html'
    queryset = Project.objects.all()

src/website/templates/website/base.html
{% load static %}
<html lang="en">
<head>

    <meta charset="utf-8"/>

    <title>CMS |
        {% block base_title %}
            Home
        {% endblock %}
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Project - Home page" name="description"/>
    <meta content="mark" name="author"/>
    <meta content="multirole-business" name="organization"/>

    <link rel="shortcut icon" href="{% static 'core/images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'core/libs/owl.carousel/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/libs/owl.carousel/assets/owl.theme.default.min.css' %}">

    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'core/css/icons.min.css' %}" rel="stylesheet"/>

    <link href="{% static 'core/css/app.min.css' %}" rel="stylesheet"/>

    {% block base_css_links %}

    {% endblock %}

</head>

<body data-spy="scroll" data-target="#topnav-menu" data-offset="60">

{% block base_header %}
    {% include 'website/include/header.html' %}
{% endblock %}

{% block base_content %}{% endblock %}

{% block base_footer %}
    {% include 'website/include/footer.html' %}
{% endblock %}

<script src="{% static 'core/libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'core/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'core/libs/metismenu/metisMenu.min.js' %}"></script>
<script src="{% static 'core/libs/simplebar/simplebar.min.js' %}"></script>
<script src="{% static 'core/libs/node-waves/waves.min.js' %}"></script>

<script src="{% static 'core/libs/jquery.easing/jquery.easing.min.js' %}"></script>

<script src="{% static 'core/libs/jquery-countdown/jquery.countdown.min.js' %}"></script>
<script src="{% static 'core/libs/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'core/js/pages/ico-landing.init.js' %}"></script>
<script src="{% static 'core/js/app.js' %}"></script>

{% block base_internal_js %}{% endblock %}

</body>
</html>
{% block base_external_js %}{% endblock %}

src/website/templates/website/home.html
{% extends 'website/base.html' %}
{% load static %}

{% block base_content %}
<!-- hero section start -->
<section class="section hero-section bg-ico-hero" id="home">
    <div class="bg-overlay bg-primary"></div>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12">
                <div class="text-white-50 text-center">
                    <h1 class="text-white font-weight-semibold mb-3 hero-title">
                        Charity management system
                    </h1>
                    <blockquote class="blockquote">
                        <p>
                            O you who believe! Do not cancel your charity by reminders of your generosity or by
                            injury, like those who spend their substance to be seen of men, but believe neither in
                            Allah nor in the Last Day
                        </p>
                        <footer class="blockquote-footer text-white">Al-Quran <cite title="Source Title">(2:264)</cite>
                        </footer>
                    </blockquote>
                    <div class="row justify-content-center">

                        <div class="cols m-2">
                            <div class="p-4 border rounded">
                                <h1 class="text-white"><i class="fa fa-users"></i></h1>
                                <p class="mb-0">00{{ users }}</p>
                            </div>
                        </div>

                        <div class="cols m-2">
                            <div class="p-4 border rounded">
                                <h1 class="text-white"><i class="fa fa-list"></i></h1>
                                <p class="mb-0">00{{ projects_count }}</p>
                            </div>
                        </div>

                        <div class="cols m-2">
                            <div class="p-4 border rounded">
                                <h1 class="text-white"><i class="fa fa-coins"></i></h1>
                                <p class="mb-0">{{ funds.donation_amount__sum }}</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>

<section class="section" id="projects">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center mb-5">
                    <div class="small-title">Most Recent</div>
                    <h4>Top Donation Project</h4>
                </div>
            </div>
        </div>
        <!-- end row -->

        <div class="col-lg-12 row">
            {% for project in projects %}
            <div class="col-4">
                <div class="card team-box">
                    <div class="card-body">

                        <div class="mt-3">
                            <h5 class="text-center">{{ project.name }}</h5>
                            <P class="text-justify mb-2">{{ project.description|truncatechars:300 }}</P>
                            Required amount : {{project.required_amount}}<br>
                            Donated amount : {{project.donation_amount}}

                            <div class="progress mt-1">
                                    <div class="progress-bar progress-bar-striped progress-bar-animated"
                                         role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"
                                         style="width: 100%"></div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-top text-center">
                        <div class="d-flex mb-0 team-social-links">
                            <div class="flex-fill">
                                <b>
                                    <a href="{% url 'website:project-detail' project.pk %}" class="text-primary">
                                        <i class="mdi mdi-link"></i> View
                                    </a>
                                </b>
                            </div>
                            <div class="flex-fill">
                                <b>
                                    <a href="{% url 'customer-portal:donate' project.pk %}" class="text-warning">
                                        <i class="fa fa-coins"></i> Donate
                                    </a>
                                </b>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>

<section class="section bg-white" id="roadmap">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center mb-5">
                    <div class="small-title">Timeline</div>
                    <h4>Development Road map</h4>
                </div>
            </div>
        </div>
        <!-- end row -->

        <div class="row mt-4">
            <div class="col-lg-12">
                <div class="hori-timeline">
                    <div class="owl-carousel owl-theme events navs-carousel" id="timeline-carousel">

                        <div class="item event-list">
                            <div>
                                <a href="#">
                                    <div class="event-date">
                                        <div class="mb-1"><i
                                                class="bx bx-calendar"></i> 5th October, 2021
                                        </div>
                                        <h5 class="mb-4">10% Project</h5>

                                    </div>
                                    <div class="event-down-icon">
                                        <i class="bx bx-down-arrow-circle h1 text-primary down-arrow-icon"></i>
                                    </div>

                                    <div class="mt-3 px-3">
                                        <p class="text-muted">
                                            Project Idea, Documentation and Presentations
                                        </p>
                                    </div>
                                </a>

                            </div>
                        </div>
                        <div class="item event-list">
                            <div>
                                <a href="#">
                                    <div class="event-date">
                                        <div class="mb-1"><i
                                                class="bx bx-calendar"></i> 21st December, 2021
                                        </div>
                                        <h5 class="mb-4">30% Project</h5>

                                    </div>
                                    <div class="event-down-icon">
                                        <i class="bx bx-down-arrow-circle h1 text-primary down-arrow-icon"></i>
                                    </div>

                                    <div class="mt-3 px-3">
                                        <p class="text-muted">
                                            Interface, Prototype, Documentation and Presentation
                                        </p>
                                    </div>
                                </a>

                            </div>
                        </div>
                        <div class="item event-list">
                            <div>
                                <a href="#">
                                    <div class="event-date">
                                        <div class="mb-1"><i
                                                class="bx bx-calendar"></i> 20th March, 2021
                                            <small>(Expected)</small>
                                        </div>
                                        <h5 class="mb-4">60% Project</h5>

                                    </div>
                                    <div class="event-down-icon">
                                        <i class="bx bx-down-arrow-circle h1 text-primary down-arrow-icon"></i>
                                    </div>

                                    <div class="mt-3 px-3">
                                        <p class="text-muted">
                                            Root Access, Admin Portal and Customer Portal
                                        </p>
                                    </div>
                                </a>

                            </div>
                        </div>
                        <div class="item event-list">
                            <div>
                                <a href="#">
                                    <div class="event-date">
                                        <div class="mb-1"><i
                                                class="bx bx-calendar"></i> 5th June, 2021 <small>(Expected)</small>
                                        </div>
                                        <h5 class="mb-4">100% Project</h5>

                                    </div>
                                    <div class="event-down-icon">
                                        <i class="bx bx-down-arrow-circle h1 text-primary down-arrow-icon"></i>
                                    </div>

                                    <div class="mt-3 px-3">
                                        <p class="text-muted">
                                            Payment System and Fully functional Live Application
                                        </p>
                                    </div>
                                </a>

                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>

<section class="section" id="projects-all">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center mb-5">
                    <div class="small-title">Need Help</div>
                    <h4>Global Donation Projects</h4>
                </div>
            </div>
        </div>

        <div class="col-lg-12 row">
            {% for project in projects %}
            <div class="col-4">
                <div class="card border">
                    <div class="card-body">

                        <div class="mt-3">
                            <h5 class="text-center">{{ project.name }}</h5>
                            <P class="text-justify mb-2">{{ project.description|truncatechars:300 }}</P>
                            Total amount : {{project.required_amount}}<br>
                            Donated amount : {{project.donation_amount}}
                               <div class="progress mt-1">
                                    <div class="progress-bar progress-bar-striped progress-bar-animated"
                                         role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"
                                         style="width: 100%"></div>
                            </div
                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-top text-center">
                        <div class="d-flex mb-0 team-social-links">
                            <div class="flex-fill">
                                <b>
                                    <a href="{% url 'website:project-detail' project.pk %}" class="text-primary">
                                        <i class="mdi mdi-link"></i> View
                                    </a>
                                </b>
                            </div>
                            <div class="flex-fill">
                                <b>
                                    <a href="{% url 'customer-portal:donate' project.pk %}" class="text-warning">
                                        <i class="fa fa-coins"></i> Donate
                                    </a>
                                </b>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</section>

{% endblock %}

src/website/templates/website/project_detail.html
{% extends 'website/base.html' %}
{% load static %}

{% block base_content %}
    <!-- hero section start -->
    <section class="section hero-section bg-ico-hero" id="home">
        <div class="bg-overlay bg-primary"></div>
        <div class="container">
            <div class="row align-items-center text-center">
                <div class="col-lg-12">
                    <div class="text-white-50">
                        <p class="my-2">({{ object.project_type }})</p>
                        <h1 class="text-white font-weight-semibold mb-1 hero-title">
                            {{ object.name }} <i class="fa fa-check-circle text-success"></i>
                        </h1>
                        <div class="row justify-content-center">

                            <div class="cols m-2">
                                <div class="p-3 border rounded">
                                    <p class="mb-0">Required Fund</p>
                                    <h1 class="text-white">{{ object.required_amount }}</h1>
                                </div>
                            </div>

                            <div class="cols m-2">
                                <div class="p-3 border rounded">
                                    <p class="mb-0">Gained Fund</p>
                                    <h1 class="text-white">{{ object.donation_amount }}</h1>
                                </div>
                            </div>

                        </div>
                        <hr>
                        <div>
                            <b>
                                <a href="{% url 'customer-portal:donate' object.pk %}" class="btn btn-danger btn-lg">
                                    <i class="fa fa-coins"></i> Donate Now
                                </a>
                            </b>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </section>

    <section class="section">
        <div class="container">

            <div class="col-lg-12">
                <p class="mb-4">{{ object.description }}</p>
                <b><i class="fa fa-pen"></i> Created On | {{ object.created_on }}</b>
            </div>
        </div>
    </section>

{% endblock %}