core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('a/', include('src.portals.admins.urls', namespace='admins')),
    path('c/', include('src.portals.customer.urls', namespace='customer-portal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portals/admins/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from .views import *

app_name = "admins"
urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('ngo/<int:pk>/change/', NGOUpdateView.as_view(), name='ngo-update'),

    path('projecttype/', ProjectTypeListView.as_view(), name='projecttype-list'),
    path('projecttype/add/', ProjectTypeCreateView.as_view(), name='projecttype-create'),
    path('projecttype/<int:pk>/change/', ProjectTypeUpdateView.as_view(), name='projecttype-update'),
    path('projecttype/<int:pk>/delete/', ProjectTypeDeleteView.as_view(), name='projecttype-delete'),

    path('project/', ProjectListView.as_view(), name='project-list'),
    path('project/add/', ProjectCreateView.as_view(), name='project-create'),
    path('project/<int:pk>/change/', ProjectUpdateView.as_view(), name='project-update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),

    path('donation/', DonationListView.as_view(), name='donation-list'),
    path('donation/<int:pk>/change/', DonationUpdateView.as_view(), name='donation-update'),
    path('donation/<int:pk>/delete/', DonationDeleteView.as_view(), name='donation-delete'),

    path('payment/verification/easypaisa/', PaymentVerificationEasyPaisa.as_view(), name='payment-verification-easypaisa')

]

src/portals/admins/templates/admins/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} {{ request.user }} {% endblock %}

{% block base_links %}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="media">
                                <div class="mr-3">
                                    {% if request.user.profile_image %}
                                        <img src="{{ request.user.profile_image.url }}" alt=""
                                             class="avatar-md rounded-circle img-thumbnail">
                                    {% else %}
                                        <img src="{% static 'images/user.png ' %}" alt=""
                                             class="avatar-md rounded-circle img-thumbnail">
                                    {% endif %}
                                </div>
                                <div class="media-body align-self-center">
                                    <div class="text-muted">
                                        <p class="mb-2">Welcome to Charity</p>
                                        <h5 class="mb-1">
                                            {% if request.user.first_name and request.user.last_name %}
                                                {{ request.user.first_name }} {{ request.user_last_name }}
                                            {% else %}
                                                {{ request.user.username }}
                                            {% endif %}
                                        </h5>
                                        <p class="mb-0 text-danger">
                                            Admin Account
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-8 align-self-center">
                            <div class="text-lg-center mt-4 mt-lg-0">
                                <div class="row text-center">
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-users"></i>
                                            </h2>
                                            <small>Total Accounts</small>
                                            <h5 class="mt-2">{{ total }}</h5>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-user-lock"></i>
                                            </h2>
                                            <small>Admins</small>
                                            <h5 class="mt-2">{{ admins }}</h5>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-user-check"></i>
                                            </h2>
                                            <small>Staff</small>
                                            <h5 class="mt-2">{{ staff }}</h5>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-user-circle"></i>
                                            </h2>
                                            <small>Customers</small>
                                            <h5 class="mt-2">{{ customers }}</h5>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-arrow-circle-down"></i>
                                            </h2>
                                            <small>Un-Verified</small>
                                            <h5 class="mt-2">{{ in_active }}</h5>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}




src/portals/admins/templates/admins/donation_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Delete {{ object }} {% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <form method="post">{% csrf_token %}
                        <p class="mb-2">Are you sure you want to delete
                            <b class="text-danger">"{{ object }}"</b>
                            ?</p>
                        <input type="submit" class="btn btn-danger" value="Confirm">
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/portals/admins/templates/admins/donation_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Update ProjectType{% endblock %}

{% block page_heading %}
    Update Donation
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admins:donation-list' %}"><i class="fa fa-arrow-left"></i> Back to List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/donation_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Donations {% endblock %}
{% block page_heading %}
    Donations
{% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="card">
        <div class="card-body">
            {% if donation_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>User</th>
                            <th>Project</th>
                            <th>Amount</th>
                            <th>TX id</th>
                            <th>Created On</th>
                            <th>Is Paid</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for row in donation_list %}
                            <tr>
                                <td>{{ row.pk }}</td>
                                <td>{{ row.user }}</td>
                                <td>{{ row.project }}</td>
                                <td>{{ row.amount }}</td>
                                <td>{{ row.transaction_id }}</td>
                                <td>{{ row.created_on }}</td>
                                <td>
                                    {% if row.is_paid %}
                                        <i class="fa fa-check text-success"></i>
                                    {% else %}
                                        <i class="fa fa-times text-danger"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if row.is_completed %}
                                        <i class="fa fa-check text-success"></i>
                                    {% else %}
                                        <i class="fa fa-times text-danger"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'admins:donation-update' row.pk %}">
                                        <i class="fa fa-edit"></i></a>
                                    <a class="text-danger"
                                       href="{% url 'admins:donation-delete' row.pk %}">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>
                <h5 class="card-title text-danger">No Transactions placed yet.</h5>
                </p>

            {% endif %}
        </div>
    </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}

src/portals/admins/templates/admins/ngo_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}NGO Update{% endblock %}

{% block page_heading %}
    NGO Update
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admins:projecttype-list' %}"><i class="fa fa-arrow-left"></i> Back to List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/project_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Delete {{ object }} {% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <form method="post">{% csrf_token %}
                        <p class="mb-2">Are you sure you want to delete
                            <b class="text-danger">"{{ object }}"</b>
                            ?</p>
                        <input type="submit" class="btn btn-danger" value="Confirm">
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/portals/admins/templates/admins/project_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Add/Update Project{% endblock %}

{% block page_heading %}
    Add/Update Project
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admins:project-list' %}"><i class="fa fa-arrow-left"></i> Back to List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/project_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Projects {% endblock %}
{% block page_heading %}
    Projects
{% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="mb-2">
        <a href="{% url 'admins:project-create' %}" class="btn btn-primary">
            <i class="fa fa-plus"></i> Add Project
        </a>
    </div>

    <div class="card">
        <div class="card-body">
            {% if project_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Amount</th>
                            <th>Donated</th>
                            <th>Created On</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for row in project_list %}
                            <tr>
                                <td>{{ row.pk }}</td>
                                <td>{{ row.name }}</td>
                                <td>{{ row.project_type }}</td>
                                <td>{{ row.required_amount }}</td>
                                <td>{{ row.donation_amount }}</td>
                                <td>{{ row.created_on }}</td>
                                <td>
                                    {% if row.is_completed %}
                                        <i class="fa fa-check text-success"></i>
                                    {% else %}
                                        <i class="fa fa-times text-danger"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'admins:project-update' row.pk %}">
                                        <i class="fa fa-edit"></i></a>
                                    <a class="text-danger"
                                       href="{% url 'admins:project-delete' row.pk %}">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>
                <h5 class="card-title text-danger">No Projects added by administration.</h5>
                </p>

            {% endif %}
        </div>
    </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}

src/portals/admins/templates/admins/projecttype_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Add/Update ProjectType{% endblock %}

{% block page_heading %}
    Add/Update ProjectType
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admins:projecttype-list' %}"><i class="fa fa-arrow-left"></i> Back to List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/projecttype_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Project Types {% endblock %}
{% block page_heading %}
    Project Type List
{% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="mb-2">
        <a href="{% url 'admins:projecttype-create' %}" class="btn btn-primary">
            <i class="fa fa-plus"></i> Add Project Type
        </a>
    </div>

    <div class="card">
        <div class="card-body">
            {% if projecttype_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Active</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for pro in projecttype_list %}
                            <tr>
                                <td>{{ pro.pk }}</td>
                                <td>{{ pro.name }}</td>
                                <td>{{ pro.description }}</td>
                                <td>
                                    {% if pro.is_active %}
                                        <i class="fa fa-check text-success"></i>
                                    {% else %}
                                        <i class="fa fa-times text-danger"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'admins:projecttype-update' pro.pk %}">
                                        <i class="fa fa-edit"></i></a>
                                    <a class="text-danger"
                                       href="{% url 'admins:projecttype-delete' pro.pk %}">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>
                <h5 class="card-title text-danger">No Project Types added by administration.</h5>
                </p>

            {% endif %}
        </div>
    </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}